networks:
  app-network:

services:
  frontend:
    ports:
      - "3000:3000"
    user: node
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: >
      sh -c "npm i && npm run dev"
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    networks:
      - app-network
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"